import { theme } from '../../shared/theme/themeContract.css'
import { flattenObject } from '../../shared/flattenObject'

const colorTokens: Record<string, unknown> = flattenObject(theme.colors)

/*
  TODO:
  - top / right / bottom / left
*/

export const styleProps = {
  color: colorTokens,
  backgroundColor: colorTokens,
  borderColor: colorTokens,
  border: theme.borders,
  borderRadius: theme.radii,
  borderWidth: theme.borderWidths,

  fontFamily: theme.fontFamilies,
  fontSize: theme.fontSizes,
  fontWeight: theme.fontWeights,

  gap: theme.space,

  lineHeight: theme.lineHeights,

  margin: theme.space,
  marginTop: theme.space,
  marginRight: theme.space,
  marginBottom: theme.space,
  marginLeft: theme.space,

  padding: theme.space,
  paddingTop: theme.space,
  paddingRight: theme.space,
  paddingBottom: theme.space,
  paddingLeft: theme.space,

  alignContent: [
    'center',
    'start',
    'end',
    'flex-start',
    'flex-end',
    'normal',
    'baseline',
    'first baseline',
    'last baseline',
    'space-between',
    'space-around',
    'space-evenly',
    'stretch',
    'safe center',
    'unsafe center',
    'inherit',
    'initial',
    'revert',
    'revert-layer',
    'unset',
  ],

  alignItems: [
    'normal',
    'stretch',
    'center',
    'start',
    'end',
    'flex-start',
    'flex-end',
    'self-start',
    'self-end',
    'baseline',
    'first baseline',
    'last baseline',
    'safe center',
    'unsafe center',
    'inherit',
    'initial',
    'revert',
    'revert-layer',
    'unset',
  ],

  alignSelf: [
    'auto',
    'normal',
    'center',
    'start',
    'end',
    'self-start',
    'self-end',
    'flex-start',
    'flex-end',
    'baseline',
    'first baseline',
    'last baseline',
    'stretch',
    'safe center',
    'unsafe center',
    'inherit',
    'initial',
    'revert',
    'revert-layer',
    'unset',
  ],

  flexDirection: [
    'row',
    'row-reverse',
    'column',
    'column-reverse',
    'inherit',
    'initial',
    'revert',
    'revert-layer',
    'unset',
  ],

  flexWrap: [
    'nowrap',
    'wrap',
    'wrap-reverse',
    'inherit',
    'initial',
    'revert',
    'revert-layer',
    'unset',
  ],

  justifyContent: [
    'center',
    'start',
    'end',
    'flex-start',
    'flex-end',
    'left',
    'right',
    'normal',
    'space-between',
    'space-around',
    'space-evenly',
    'stretch',
    'safe center',
    'unsafe center',
    'inherit',
    'initial',
    'revert',
    'revert-layer',
    'unset',
  ],

  justifyItems: [
    'normal',
    'stretch',
    'center',
    'start',
    'end',
    'flex-start',
    'flex-end',
    'self-start',
    'self-end',
    'left',
    'right',
    'baseline',
    'first baseline',
    'last baseline',
    'safe center',
    'unsafe center',
    'legacy right',
    'legacy left',
    'legacy center',
    'inherit',
    'initial',
    'revert',
    'revert-layer',
    'unset',
  ],

  boxSizing: ['border-box', 'content-box', 'inherit', 'initial', 'revert', 'revert-layer', 'unset'],

  position: [
    'static',
    'relative',
    'absolute',
    'fixed',
    'sticky',
    'inherit',
    'initial',
    'revert',
    'revert-layer',
    'unset',
  ],

  display: [
    'block',
    'block flex',
    'block flow',
    'block flow-root',
    'block grid',
    'contents',
    'flex',
    'flow-root',
    'grid',
    'inherit',
    'initial',
    'inline',
    'inline flex',
    'inline flow',
    'inline flow-root',
    'inline grid',
    'inline-block',
    'inline-flex',
    'inline-grid',
    'list-item',
    'none',
    'revert',
    'revert-layer',
    'table',
    'table-row-group',
    'table-header-group',
    'table-footer-group',
    'table-row',
    'table-cell',
    'table-column-group',
    'table-column',
    'table-caption',
    'unset',
  ],
}

export const stylePropShorthands = {
  m: ['margin'],
  mt: ['marginTop'],
  mr: ['marginRight'],
  mb: ['marginBottom'],
  ml: ['marginLeft'],
  mx: ['marginLeft', 'marginRight'],
  my: ['marginTop', 'marginBottom'],

  p: ['padding'],
  pt: ['paddingTop'],
  pr: ['paddingRight'],
  pb: ['paddingBottom'],
  pl: ['paddingLeft'],
  px: ['paddingLeft', 'paddingRight'],
  py: ['paddingTop', 'paddingBottom'],
}
