name: 'Storybook Tests'

on:
  push:
    branches: [main, canary]
  pull_request:
    branches: [main, canary]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build SDK
        run: pnpm turbo build
      - name: Install Playwright
        working-directory: ./apps/smithy
        run: pnpm exec playwright install --with-deps
      - name: Build Storybook
        working-directory: ./apps/smithy
        run: pnpm build-storybook --quiet
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            cd ./apps/smithy; \
            pnpm dlx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "pnpm dlx http-server storybook-static --port 6006 --silent" \
            "pnpm dlx wait-on tcp:127.0.0.1:6006 && pnpm test-storybook"
